[versions]
kotlin = "1.7.20"
kotest = "5.5.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlin-serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"

junit-engine = "org.junit.jupiter:junit-jupiter-engine:5.9.1"

kotest-api = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
